export type LearningTab = 'learn' | 'glossary' | 'implementation';

export interface GlossaryEntry {
  id: string;
  term: string;
  symbol?: string;
  short: string;
  tooltip?: string;
  meaning: string;
  formula?: string;
  implementation?: string;
  experiment?: string;
  caveat?: string;
  related: string[];
  primaryTab: LearningTab;
}

export const glossaryEntries: GlossaryEntry[] = [
  {
    id: 'physical-picture',
    term: 'Reading the string',
    symbol: '\\(y(\\sigma, \\tau)\\)',
    short: 'A map of the string’s displacement at each position and time.',
    meaning: '\\(\\sigma\\) labels a position along the string, \\(\\tau\\) labels time, and \\(y(\\sigma, \\tau)\\) tells us how far that position is displaced transversely. The simulator turns this function into a moving curve and a spacetime history.',
    experiment: 'Choose a normal-mode preset, press Play, and compare the curve now with its later worldsheet trace.',
    related: ['string-profile', 'worldsheet', 'normal-modes'],
    primaryTab: 'learn',
  },
  {
    id: 'string-profile',
    term: 'String profile',
    symbol: '\\(y(\\sigma, \\tau_0)\\)',
    short: 'The shape of the whole string right now.',
    meaning: 'The profile is one time-slice of the simulation, namely \\(y(\\sigma,\\tau_0)\\). Moving horizontally follows the string from one end to the other; moving vertically measures transverse displacement from the equilibrium line.',
    implementation: 'The canvas draws the solver’s current array of displacement samples, with a smooth curve between adjacent grid points.',
    experiment: 'Pause the simulation, then use a different preset to see how a changed initial shape changes the profile.',
    related: ['physical-picture', 'worldsheet', 'boundary-conditions'],
    primaryTab: 'learn',
  },
  {
    id: 'worldsheet',
    term: 'Worldsheet',
    symbol: '\\(y(\\sigma, \\tau)\\)',
    short: 'The history of every point on the string, shown as a heatmap.',
    meaning: 'The worldsheet stacks many string profiles over time. Horizontal position is \\(\\sigma\\), vertical position is \\(\\tau\\), and colour represents \\(y(\\sigma,\\tau)\\). Diagonal features reveal travelling disturbances; repeating bands reveal standing modes.',
    implementation: 'The solver retains a rolling sequence of timestamped displacement arrays. The worldsheet renderer maps that history to a colour field over the visible time window.',
    experiment: 'Run a travelling-pulse preset and follow its diagonal colour trace. Then compare it with a standing-wave preset.',
    caveat: 'This is a visual history of a one-dimensional teaching model, not an embedded relativistic string worldsheet in target spacetime.',
    related: ['physical-picture', 'string-profile', 'normal-modes'],
    primaryTab: 'learn',
  },
  {
    id: 'probe-trajectory',
    term: 'Probe trajectory',
    symbol: '\\(y(\\sigma_\\ast, \\tau)\\)',
    short: 'The displacement through time of one selected position on the string.',
    meaning: 'Choose a fixed worldsheet coordinate \\(\\sigma_\\ast\\). The probe trajectory is the one-dimensional time series \\(y(\\sigma_\\ast,\\tau)\\), obtained by following that same labelled point through the evolving profile. The cyan marker, vertical worldsheet line, and cyan trace represent one and the same \\(\\sigma_\\ast\\).',
    formula: '\\(\\gamma_{\\sigma_\\ast}: \\tau \\mapsto y(\\sigma_\\ast,\\tau)\\)',
    implementation: 'The simulator records one timestamped displacement sample from the selected grid index after each completed solver step. The probe buffer is bounded to the same 200-sample rolling window used by the worldsheet history, while remaining independent of the full two-dimensional history.',
    experiment: 'Choose a travelling pulse, press Play, and drag the cyan marker. At a fixed \\(\\sigma_\\ast\\), the trace shows when the pulse reaches that position and how the reflected pulse returns.',
    caveat: 'This graph is a displacement-versus-time projection of one selected worldsheet coordinate. It is not an additional spacetime dimension and does not by itself establish a relativistic proper-time trajectory.',
    related: ['string-profile', 'worldsheet', 'physical-picture'],
    primaryTab: 'glossary',
  },
  {
    id: 'normal-modes',
    term: 'Normal modes',
    symbol: '\\(y_n(\\sigma,\\tau)\\)',
    short: 'Special standing-wave patterns allowed by the string’s boundary conditions.',
    meaning: 'A normal mode oscillates with a stable spatial shape. For fixed ends, the spatial pattern is proportional to \\(\\sin(n\\pi\\sigma/L)\\). The fundamental has one broad arch; higher modes have more nodes, points that remain at \\(y=0\\).',
    experiment: 'Compare Fundamental standing wave with Third normal mode. Count the interior nodes and watch how the frequency changes.',
    related: ['boundary-conditions', 'string-profile', 'wave-speed'],
    primaryTab: 'learn',
  },
  {
    id: 'initial-conditions',
    term: 'Preset and initial conditions',
    symbol: '\\(y(\\sigma,0),\\;\\partial_\\tau y(\\sigma,0)\\)',
    short: 'A preset supplies the initial shape and, where needed, initial transverse velocity.',
    tooltip: 'Choose the starting shape and motion for the string.',
    meaning: 'The reference modes use an initial displacement \\(y(\\sigma,0)\\) and, where needed, an initial transverse velocity \\(\\partial_\\tau y(\\sigma,0)\\). T18 instead starts from closed unit-tangent sectors whose even harmonics preserve periodic closure and the conformal constraints.',
    implementation: 'Selecting a preset resets the solver. In the reference modes it evaluates the displacement and optional velocity functions at all 256 grid points. In T18 it selects one of eight labelled tangent constructions adapted to the active topology: periodic closed loop, fixed/free/mixed open endpoints, or an anti-periodic reference cell.',
    caveat: 'The T18 presets are not open-string pluck or Gaussian profiles copied into the nonlinear solver. Each boundary gets a constraint-compatible tangent construction, while the anti-periodic option closes only after its doubled length-2L extension.',
    experiment: 'Compare a centred Gaussian pulse with the right-moving Gaussian packet. Predict which has nonzero initial \\(\\partial_\\tau y\\), then watch the worldsheet.',
    related: ['normal-modes', 'wave-speed', 'playback-rate'],
    primaryTab: 'glossary',
  },
  {
    id: 'classical-model',
    term: 'Classical string model',
    symbol: '\\(\\partial_\\tau^2y=c^2\\partial_\\sigma^2y-\\gamma\\partial_\\tau y\\)',
    short: 'A discretised model of small transverse waves on an ideal classical string.',
    tooltip: 'Use tension, density, and damping to control a classical wave equation.',
    meaning: 'Classical mode evolves small transverse displacement with tension \\(T\\), linear mass density \\(\\mu\\), and optional damping \\(\\gamma\\). Its wave speed is \\(c=\\sqrt{T/\\mu}\\).',
    implementation: 'The code uses a central finite-difference stencil and recalculates \\(c\\) and the conservative timestep whenever length, tension, or density changes.',
    caveat: 'This is an idealised one-dimensional teaching model. It omits bending stiffness, nonlinear geometric effects, and coupling to an external medium.',
    related: ['relativistic-model', 'tension', 'mass-density', 'damping'],
    primaryTab: 'glossary',
  },
  {
    id: 'relativistic-model',
    term: 'Linearized relativistic teaching model',
    symbol: '\\(\\partial_\\tau^2y=\\partial_\\sigma^2y,\\quad c=1\\)',
    short: 'A linear transverse wave model in natural units, not a full interacting quantum string calculation.',
    tooltip: 'Use the linearized natural-unit teaching model with \\(c=1\\).',
    meaning: 'Relativistic mode fixes \\(T=\\mu=1\\) and \\(\\gamma=0\\), so the transverse wave speed is \\(c=1\\) in natural units. It is intended to connect the simulator’s worldsheets to a controlled linear approximation.',
    implementation: 'The solver uses the same central-difference structure with \\(\\lambda=\\Delta\\tau/\\Delta\\sigma\\) and checks that the sampled transverse velocity remains no greater than one.',
    caveat: 'The implementation is not a nonlinear Nambu-Goto solver and does not compute a quantum spectrum, interactions, scattering amplitudes, or target-space embeddings.',
    related: ['classical-model', 'courant-condition', 'worldsheet'],
    primaryTab: 'glossary',
  },
  {
    id: 'nonlinear-classical-model',
    term: 'Nonlinear classical conformal-gauge model',
    symbol: '\\(X^\\mu(\\sigma,\\tau),\\quad \\partial_\\tau X\\cdot\\partial_\\sigma X=0\\)',
    short: 'A separate classical closed-string embedding with explicit conformal constraints.',
    tooltip: 'Explore the constrained classical T18 embedding; it is not quantum or interacting.',
    meaning: 'The T18 mode evolves a constrained string in flat 2+1-dimensional Minkowski spacetime using conformal gauge and natural units. Periodic data form a closed loop; fixed, free, and mixed data form open endpoint problems; anti-periodic data are a reference cell whose target-space curve closes only after doubling its length.',
    formula: '\\(\\partial_\\tau X\\cdot\\partial_\\sigma X=0,\\qquad (\\partial_\\tau X)^2+(\\partial_\\sigma X)^2=1\\)',
    implementation: 'The solver transports left- and right-moving unit tangent fields, reconstructs the embedding, and reports orthogonality, normalization, closure or endpoint residuals, and boundary energy flux alongside conserved conformal-gauge energy. The simulator exposes periodic, fixed, free, mixed, and anti-periodic-cell choices; the selected preset is adapted to the active topology before initialization.',
    caveat: 'This is a classical flat-spacetime model. Crossings in the displayed projection are allowed configurations, but no reconnection or string interaction is calculated. The anti-periodic option is a doubled-domain cell, not an ordinary length-L closed loop; target-space forcing remains a separate validation task.',
    related: ['relativistic-model', 'courant-condition', 'worldsheet'],
    primaryTab: 'implementation',
  },
  {
    id: 'geometric-mode-mixing',
    term: 'Geometric mode mixing',
    symbol: '\\(\\rho(\\sigma,\\tau)=\\sqrt{X(\\sigma,\\tau)^2+Y(\\sigma,\\tau)^2}\\)',
    short: 'A nonlinear observable can combine several visible harmonics even when the underlying tangent sectors travel independently.',
    meaning: 'In T18, the left- and right-moving unit tangent fields are transported separately. The reconstructed embedding and its radial profile \\(\\rho\\) are nonlinear functions of those fields, so a Fourier analysis of \\(\\rho\\) can show changing higher-harmonic content.',
    implementation: 'The audit samples the radial profile at reset and after a fixed number of characteristic steps, then compares the fraction of radial harmonic power above the first two harmonics.',
    caveat: 'This is geometric mode mixing inside a classical flat-spacetime observable. It is not a quantum transition, string splitting, reconnection, or an interacting-string calculation.',
    related: ['nonlinear-classical-model', 'frequency-spectrum'],
    primaryTab: 'implementation',
  },
  {
    id: 'anti-periodic-sector',
    term: 'Anti-periodic field sector',
    symbol: '\\(f(\\sigma+L)=-f(\\sigma)\\)',
    short: 'A sign-reversing field identification across one reference cell.',
    meaning: 'An anti-periodic field returns with the opposite sign after one length-$L$ cell. In the linear reference path this supports half-integer spatial modes such as \\(\\cos(\\pi\\sigma/L)\\).',
    implementation: 'The T17 reference fixture evolves one cell with sign-reversing ghost samples. T18 uses the same cell interpretation in its anti-periodic selector, adapts the chosen preset to that cell, and renders the sign-reversed length-$2L$ extension as the target-space curve.',
    caveat: 'T18 adopts the doubled-domain interpretation: the sign-reversed cell is extended to a length-$2L$ periodic domain before calling the target-space curve closed. This remains a classical geometric construction, not a twisted-sector quantum calculation.',
    related: ['boundary-conditions', 'nonlinear-classical-model', 'normal-modes'],
    primaryTab: 'implementation',
  },
  {
    id: 'quantum-string-state',
    term: 'Finite free-string state',
    symbol: '\\(|\\{N_n\\}_L;\\{N_n\\}_R\\rangle\\)',
    short: 'A bounded occupation-number description of a free closed-string state.',
    meaning: 'T19 uses a bosonic closed string in flat 26-dimensional spacetime, represented in light-cone oscillator bookkeeping. Each displayed occupation says how many excitations occupy a mode in the left- or right-moving sector.',
    implementation: 'The explorer keeps modes \\(n=1,2,3,4\\) and allows occupations from 0 through 2. Its finite free layer applies exact phases from the declared dimensionless Hamiltonian \\(H_{\\mathrm{free}}=N_L+N_R\\) to normalized matched superpositions and reports basis-state probabilities.',
    caveat: 'The finite layer does not enumerate the unbounded Hilbert space, infer a spatial probability density, or model interactions and driven backgrounds.',
    related: ['level-matching', 'free-string-evolution', 'relativistic-model'],
    primaryTab: 'learn',
  },
  {
    id: 'free-string-evolution',
    term: 'Finite free-string evolution',
    symbol: '\\(a_j(\\tau)=a_j(0)e^{-i\\omega_j\\tau},\\quad H_{\\mathrm{free}}=N_L+N_R\\)',
    short: 'Exact phase rotation inside the bounded educational state basis.',
    meaning: 'A finite superposition can be evolved by multiplying each matched basis-state amplitude by a phase. The phase frequency is the declared dimensionless sum of its left and right oscillator levels.',
    implementation: 'T19 normalizes the selected finite superposition, applies the phase analytically, and displays phase angle, complex amplitude, frequency, norm, relative phase, and basis-state probability at the chosen time.',
    caveat: 'This is a bookkeeping Hamiltonian for the teaching layer, not a general quantized-string Hamiltonian or a spatial wavefunction. The mode and occupation cutoff remains visible.',
    related: ['quantum-string-state', 'level-matching'],
    primaryTab: 'glossary',
  },
  {
    id: 'level-matching',
    term: 'Closed-string level matching',
    symbol: '\\(N_L=\\sum_n nN_{n,L},\\quad N_R=\\sum_n nN_{n,R},\\quad N_L=N_R\\)',
    short: 'The left- and right-moving oscillator levels must agree for the bounded closed-string examples shown here.',
    meaning: 'The two sectors carry separate oscillator occupations. Their weighted sums are the left and right levels. The equality \\(N_L=N_R\\) is the displayed closed-string physical-state condition in this light-cone representation.',
    formula: '\\(M^2=\\frac{4}{\\alpha\\prime}(N_L+N_R-2),\\quad \\alpha\\prime=1\\text{ here}\\)',
    implementation: 'The T19 selector marks unequal levels invalid and only shows a mass-squared value for level-matched examples.',
    caveat: 'This finite display uses one stated bosonic convention. It is not a general treatment of all gauge, null-state, polarization, or supersymmetry constraints.',
    related: ['quantum-string-state'],
    primaryTab: 'glossary',
  },
  {
    id: 'worldsheet-topology',
    term: 'Perturbative worldsheet topology',
    symbol: '\\(\\Sigma\\)',
    short: 'The surface that represents a possible string history in a perturbative interaction picture.',
    meaning: 'A propagating free string sweeps out a strip or cylinder. A splitting or joining process is represented by a pair-of-pants surface, while loop corrections add handles. The surface is a conceptual history, not a local splitting rule in the current simulator.',
    implementation: 'T20 supplies static accessible SVG diagrams and labels their process and topology. It does not evaluate an amplitude or integrate over worldsheet moduli.',
    caveat: 'The diagrams do not calculate scattering probabilities, path integrals, non-perturbative dynamics, or a string interaction.',
    related: ['quantum-string-state', 'nonlinear-classical-model'],
    primaryTab: 'learn',
  },
  {
    id: 'string-length',
    term: 'String length',
    symbol: '\\(L\\)',
    short: 'The coordinate length from \\(\\sigma=0\\) to \\(\\sigma=L\\).',
    tooltip: 'Set the length of the simulated string.',
    meaning: 'Length fixes the interval on which the profile is sampled. For fixed ends, increasing \\(L\\) lowers the fundamental frequency at fixed wave speed.',
    formula: '\\(f_1=\\frac{c}{2L}\\)',
    implementation: 'The simulator keeps \\(N=256\\) grid points and recalculates \\(\\Delta\\sigma=L/(N-1)\\) and the stable timestep whenever \\(L\\) changes.',
    experiment: 'Use the fundamental standing-wave preset, double \\(L\\), and compare the rate of oscillation.',
    related: ['fundamental-frequency', 'numerical-grid', 'time-step'],
    primaryTab: 'glossary',
  },
  {
    id: 'damping',
    term: 'Damping',
    symbol: '\\(\\gamma\\)',
    short: 'A classical loss term that gradually reduces the amplitude and energy of the toy model.',
    tooltip: 'Add classical damping; it is disabled in relativistic mode.',
    meaning: 'Damping is modelled by \\(-\\gamma\\partial_\\tau y\\). It represents phenomenological energy loss rather than a microscopic interaction.',
    implementation: 'In classical mode the solver scales the interior velocity contribution each timestep. Relativistic mode fixes \\(\\gamma=0\\), so the control is disabled there.',
    experiment: 'Run a pluck with \\(\\gamma=0\\), reset, then repeat with a larger \\(\\gamma\\). Compare the energy diagnostic and the fading profile.',
    caveat: 'Damping deliberately breaks energy conservation; it should not be interpreted as fundamental relativistic-string dynamics.',
    related: ['classical-model', 'total-energy', 'relativistic-model'],
    primaryTab: 'glossary',
  },
  {
    id: 'playback-rate',
    term: 'Playback time scale',
    symbol: '\\(s_{\\mathrm{play}}\\)',
    short: 'A display-rate multiplier that changes how many solver steps advance per animation frame.',
    tooltip: 'Change the animation rate without changing the numerical timestep.',
    meaning: 'Playback time scale changes the apparent speed of the animation, not the physical parameters or the integration timestep \\(\\Delta\\tau\\).',
    implementation: 'Each animation frame accumulates a fractional count of solver steps from the selected scale, then advances whole steps when available.',
    related: ['time-step', 'courant-condition'],
    primaryTab: 'glossary',
  },
  {
    id: 'total-energy',
    term: 'Total energy',
    symbol: '\\(E=E_{\\mathrm{kin}}+E_{\\mathrm{pot}}\\)',
    short: 'The displayed sum of kinetic and strain energy in the current discrete state.',
    tooltip: 'See the current kinetic-plus-strain energy of the simulated string.',
    meaning: 'The energy diagnostic combines motion and spatial deformation. In an undamped classical run it should be approximately conserved; damping makes it decrease.',
    formula: '\\(E_{\\mathrm{kin}}\\approx\\frac12\\sum_i\\mu v_i^2\\Delta\\sigma,\\quad E_{\\mathrm{pot}}\\approx\\frac12\\sum_iT\\left(\\frac{y_i-y_{i-1}}{\\Delta\\sigma}\\right)^2\\Delta\\sigma\\)',
    implementation: 'The displayed value is calculated from the current solver arrays at every advancing animation frame. It is a numerical diagnostic, not a quantum-string energy spectrum.',
    related: ['damping', 'energy-density', 'finite-difference-update'],
    primaryTab: 'glossary',
  },
  {
    id: 'fundamental-frequency',
    term: 'Fundamental frequency',
    symbol: '\\(f_1\\)',
    short: 'The lowest standing-wave frequency predicted for the selected boundary condition.',
    tooltip: 'See the lowest predicted standing-wave frequency.',
    meaning: 'With fixed or free ends the displayed fundamental is \\(f_1=c/(2L)\\). With the mixed endpoint rule it is \\(f_1=c/(4L)\\).',
    implementation: 'The live diagnostic evaluates this from the current wave speed, length, and selected boundary condition; it is not fitted from the animated trace.',
    related: ['normal-modes', 'boundary-conditions', 'string-length', 'wave-speed'],
    primaryTab: 'glossary',
  },
  {
    id: 'energy-density',
    term: 'Energy-density strip',
    symbol: '\\(\\mathcal{E}(\\sigma,\\tau_0)\\)',
    short: 'A relative colour strip beneath the profile showing where the current discrete energy is concentrated.',
    tooltip: 'See where the current profile carries more or less computed energy.',
    meaning: 'Brighter regions indicate larger local values of the classical energy-density estimate. Motion contributes through \\(v^2\\); local slope contributes through \\((\\partial_\\sigma y)^2\\).',
    formula: '\\(\\mathcal{E}\\approx\\tfrac12\\mu(\\partial_\\tau y)^2+\\tfrac12T(\\partial_\\sigma y)^2\\)',
    implementation: 'The profile renderer computes centred slopes for interior points and maps the current values relative to that frame’s maximum. It is a relative visual aid; the strip does not currently provide an absolute colour bar.',
    caveat: 'The displayed strip uses the classical parameter expression in both modes, so it should not be read as a complete relativistic energy density.',
    related: ['total-energy', 'string-profile', 'classical-model'],
    primaryTab: 'glossary',
  },
  {
    id: 'worldsheet-fields',
    term: 'Worldsheet fields',
    symbol: '\\(y,\\;\\partial_\\tau y,\\;\\mathcal{E},\\;\\partial_\\sigma y\\)',
    short: 'Choose which computed quantity determines the worldsheet colour.',
    meaning: 'Displacement shows the wave itself. Velocity highlights turning points and moving packets. Energy density shows where motion and strain are concentrated. Local slope highlights steepening and mode structure.',
    implementation: 'Velocity is reconstructed from neighbouring timestamped history samples; slope uses neighbouring spatial samples; energy combines their squared values with the current mass density and tension. Signed fields use a symmetric cyan/magenta scale, while energy uses a sequential dark-to-warm scale.',
    caveat: 'The display is derived from the bounded, spatially down-sampled rendering history, so it is an educational diagnostic rather than a high-precision post-processing tool.',
    related: ['worldsheet', 'energy-density', 'history-window'],
    primaryTab: 'glossary',
  },
  {
    id: 'max-transverse-speed',
    term: 'Maximum transverse speed',
    symbol: '\\(\\max_\\sigma |\\partial_\\tau y|\\)',
    short: 'The largest sampled transverse velocity along the current string.',
    meaning: 'This metric reports the greatest absolute value in the solver velocity array. In the natural-unit relativistic teaching mode, values above one signal that the linearized approximation or numerical run should be treated cautiously.',
    implementation: 'It is recalculated from the current state after every advancing animation frame.',
    caveat: 'A value at or below one is a useful local check, not a proof of full relativistic causality or the Virasoro constraints.',
    related: ['relativistic-model', 'courant-condition'],
    primaryTab: 'glossary',
  },
  {
    id: 'energy-drift',
    term: 'Energy drift',
    symbol: '\\(\\Delta E/E_0\\)',
    short: 'The relative change in total energy since the latest reset.',
    meaning: 'For an undamped relativistic teaching-model run, total discrete energy should remain approximately constant. This diagnostic compares the current value with the value immediately after reset.',
    formula: '\\(\\Delta E/E_0=(E(\\tau)-E_0)/E_0\\)',
    implementation: 'The display is green below 1% absolute drift, amber below 5%, and red at or above 5%. It appears only in relativistic mode because classical damping can intentionally remove energy.',
    related: ['total-energy', 'relativistic-model', 'courant-condition'],
    primaryTab: 'glossary',
  },
  {
    id: 'frequency-spectrum',
    term: 'Probe frequency spectrum',
    symbol: '\\(P(f)=|\\mathcal{F}[y(\\sigma_\\ast,\\tau)]|^2\\)',
    short: 'A power spectrum of the selected point’s recent displacement history.',
    meaning: 'The spectrum decomposes the recent probe trajectory into frequency components. A tall peak means that a periodic component is especially prominent in that short time window.',
    formula: '\\(P(f)=|\\mathcal{F}[y(\\sigma_\\ast,\\tau)-\\overline{y}]|^2\\)',
    implementation: 'After at least 16 evenly spaced probe samples, the app removes the sample mean, applies a Hann window, zero-pads to a power of two, and plots the positive-frequency FFT power. The highlighted bar is the largest nonzero-frequency bin.',
    caveat: 'Frequency resolution is limited by the 200-sample rolling window and its duration. This is a numerical analysis of one classical or linearized probe signal, not a quantum-string spectrum or a catalogue of particle states.',
    related: ['probe-trajectory', 'fundamental-frequency', 'history-window'],
    primaryTab: 'glossary',
  },
  {
    id: 'tension',
    term: 'String tension',
    symbol: '\\(T\\)',
    short: 'Greater tension makes disturbances propagate faster.',
    meaning: 'Tension is the restoring force that pulls a displaced string back toward its equilibrium shape. Raising it increases the classical wave speed when mass density stays fixed.',
    formula: '\\(c = \\sqrt{T / \\mu}\\)',
    implementation: 'In classical mode, the application recalculates \\(c\\) and the conservative stable timestep after tension changes. In the linearized relativistic teaching mode, natural-unit parameters are fixed.',
    experiment: 'In Classical mode, raise tension and restart a travelling pulse. Compare how quickly it reaches the far end.',
    related: ['wave-speed', 'mass-density', 'courant-condition'],
    primaryTab: 'glossary',
  },
  {
    id: 'mass-density',
    term: 'Linear mass density',
    symbol: '\\(\\mu\\)',
    short: 'More mass per unit length makes the classical string respond more slowly.',
    meaning: 'Linear mass density \\(\\mu\\) describes how much inertial mass the string has along its length. Increasing \\(\\mu\\) lowers the wave speed when tension is fixed.',
    formula: '\\(c = \\sqrt{T / \\mu}\\)',
    related: ['tension', 'wave-speed'],
    primaryTab: 'glossary',
  },
  {
    id: 'boundary-conditions',
    term: 'Boundary conditions',
    symbol: '\\(y(0,\\tau),\\;y(L,\\tau)\\)',
    short: 'Rules at the string’s ends that determine reflection and allowed standing waves.',
    meaning: 'Fixed ends impose \\(y(0,\\tau)=y(L,\\tau)=0\\). Free ends impose vanishing endpoint slope, \\(\\partial_\\sigma y=0\\). Mixed ends combine the two. Periodic boundaries identify the two ends for a closed linear reference loop. Anti-periodic boundaries reverse the field sign after one reference cell and require a doubled domain for a closed T18 target-space curve. These rules change how pulses reflect and which normal modes fit on the string.',
    implementation: 'Every solver step applies the selected endpoint rule after calculating the interior update. The periodic reference keeps a duplicate endpoint for the profile display while updating the unique samples as a ring. T18 applies fixed/free/mixed endpoint relations to its characteristic fields and renders an anti-periodic cell with 2N target-space samples.',
    experiment: 'Send a pulse toward an end, then repeat with a different boundary condition and compare the reflected shape.',
    related: ['normal-modes', 'string-profile', 'wave-speed'],
    primaryTab: 'glossary',
  },
  {
    id: 'wave-speed',
    term: 'Wave speed',
    symbol: '\\(c\\)',
    short: 'The speed at which small classical disturbances travel along the string.',
    meaning: 'For an ideal classical string, tension supplies the restoring force and mass density supplies inertia. Their ratio sets the speed of small transverse waves.',
    formula: '\\(c = \\sqrt{T / \\mu}\\)',
    implementation: 'The live diagnostic reads \\(c\\) from the solver metric. The same speed determines a conservative timestep for the explicit classical update.',
    related: ['tension', 'mass-density', 'courant-condition'],
    primaryTab: 'glossary',
  },
  {
    id: 'courant-condition',
    term: 'Courant condition',
    symbol: '\\(\\lambda = c\\,\\Delta\\tau / \\Delta\\sigma\\)',
    short: 'A numerical-stability measure for the explicit time-stepping scheme.',
    meaning: 'The Courant number compares how far a disturbance can travel in one timestep with the grid spacing. It is a property of the numerical method, not a new physical observable of string theory.',
    formula: '\\(\\lambda = c\\,\\Delta\\tau / \\Delta\\sigma \\leq 1\\)',
    implementation: 'The simulator chooses a conservative timestep with \\(\\lambda = 0.5\\) for the current grid and wave speed. The solver also protects the relativistic update against a violated Courant limit.',
    caveat: 'Meeting the Courant condition prevents one kind of numerical instability; it does not by itself prove that a simulation represents full relativistic string dynamics.',
    related: ['wave-speed', 'finite-difference-update'],
    primaryTab: 'implementation',
  },
  {
    id: 'numerical-grid',
    term: 'Numerical grid',
    symbol: '\\(N=256,\\quad\\Delta\\sigma=\\frac{L}{N-1}\\)',
    short: 'The fixed set of spatial samples used to approximate the continuous string.',
    tooltip: 'The string is represented by 256 equally spaced samples.',
    meaning: 'The simulator replaces the continuous coordinate \\(\\sigma\\in[0,L]\\) with \\(N=256\\) samples. Neighbouring samples are separated by \\(\\Delta\\sigma\\), which changes when \\(L\\) changes.',
    implementation: 'Profile and solver arrays have one value per grid point. The worldsheet renderer down-samples the spatial history for display, but the solver itself advances every grid point.',
    related: ['string-length', 'time-step', 'finite-difference-update'],
    primaryTab: 'implementation',
  },
  {
    id: 'time-step',
    term: 'Numerical timestep',
    symbol: '\\(\\Delta\\tau\\)',
    short: 'The small increment of simulation time used by one finite-difference update.',
    tooltip: 'The solver advances in small stable time increments.',
    meaning: 'The timestep controls numerical resolution and stability. It is distinct from the playback time scale, which controls how quickly the accumulated steps are shown.',
    formula: '\\(\\Delta\\tau=\\frac{\\Delta\\sigma}{2c}\\quad\\text{(classical)},\\qquad\\Delta\\tau=\\frac{\\Delta\\sigma}{2}\\quad\\text{(relativistic)}\\)',
    implementation: 'The core chooses the conservative \\(\\lambda=0.5\\) timestep after changes to length, tension, density, or mode.',
    related: ['courant-condition', 'playback-rate', 'numerical-grid'],
    primaryTab: 'implementation',
  },
  {
    id: 'history-window',
    term: 'Rolling history window',
    symbol: '\\(\\{y(\\sigma,\\tau_j)\\}_{j=1}^{200}\\)',
    short: 'The most recent 200 timestamped solver states retained for the worldsheet and probe.',
    tooltip: 'The worldsheet and probe show a finite rolling history, not the entire run.',
    meaning: 'The worldsheet is built from a bounded history rather than every state since reset. As new samples arrive, the oldest retained sample is discarded; the visible time span therefore depends on \\(\\Delta\\tau\\).',
    implementation: 'Both solvers store 200 timestamped displacement arrays. The probe keeps an independent 200-sample scalar history at the selected index.',
    caveat: 'The rendered worldsheet is a finite recent window and may be spatially down-sampled for display; it is not a complete record of the simulation.',
    related: ['worldsheet', 'probe-trajectory', 'time-step'],
    primaryTab: 'implementation',
  },
  {
    id: 'finite-difference-update',
    term: 'Finite-difference update',
    symbol: '\\(y_i^{n+1}\\)',
    short: 'The numerical rule that advances the string one small timestep at a time.',
    meaning: 'The continuous wave equation \\(\\partial_\\tau^2 y = c^2\\partial_\\sigma^2 y\\) is approximated on a grid of spatial samples and discrete timesteps. Each new displacement \\(y_i^{n+1}\\) is calculated from nearby points and the preceding time state.',
    formula: '\\(y_i^{n+1}=2y_i^n-y_i^{n-1}+\\lambda^2\\left(y_{i-1}^n-2y_i^n+y_{i+1}^n\\right)\\)',
    implementation: 'Each spatial Laplacian is evaluated from an immutable snapshot of the current displacement slice. This avoids accidentally reading an already-updated neighbouring point and preserves the intended central stencil.',
    related: ['courant-condition', 'worldsheet'],
    primaryTab: 'implementation',
  },
];

export function getGlossaryEntry(id: string): GlossaryEntry | undefined {
  return glossaryEntries.find(entry => entry.id === id);
}
